language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/
  - phpunit

notifications:
  email:
    - lars@strojny.net

matrix:
  allow_failures:
    - php: hhvm
