language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
